#!/bin/bash

#copy the conf file
rm -rf /etc/httpd/conf.d/iiab.conf
cp /media/usb0/XC/xc-iiab/iiab.conf /etc/httpd/conf.d/
#copy the iiab folder to /library
rm -rf /library/iiab-venv
cp -r /media/usb0/XC/xc-iiab/iiab-venv /library/
chown -R apache:apache /library/iiab-venv
