#!/bin/bash

#copy the conf file
rm -rf /etc/httpd/conf.d/homeview.conf
cp /media/usb0/XC/xc-homeview/homeview.conf /etc/httpd/conf.d/
#copy the homeview folder to /library
rm -rf /library/homeview
cp -r /media/usb0/XC/xc-homeview/homeview /library/
chown -R apache:apache /library/homeview
